name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        shell: bash -l {0}
        run: |
          python setup.py build
      - name: Test
        env:
          DCACHE_API_URL: ${{ secrets.DCACHE_API_URL }}
          DCACHE_WEBDAV_URL: ${{ secrets.DCACHE_WEBDAV_URL }}
          DCACHE_TOKEN: ${{ secrets.DCACHE_TOKEN }}
        shell: bash -l {0}
        run: |
          python setup.py test
